[project]
name = "ag-bot"
version = "0.1.0"
description = ""
readme = "README.md"
authors = [
    { name = "ph-nixx", email = "pmiller0706@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
ag-bot = "ag_bot:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
